FROM node:10.15-jessie
RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list
RUN apt-get update && apt-get install libssl-dev
WORKDIR /usr/app
COPY . .
RUN npm install
CMD ./scripts/subscription_scheduler.js
